### ISSUE TITLE
Constructing T2-like diagram

### ISSUE THREAD

**Issue by zww-4855** [edeprince3/pdaggerq#30]
Hi all

I am trying to build the diagram attached in the pdf [T2likeDiagram.pdf](https://github.com/edeprince3/pdaggerq/files/10229204/T2likeDiagram.pdf) I tried the following implementation, but I think it abstracts too much detail. I think the issue originates in storing Wn(T2^2/2)c as an intermediate T4.  

```
import pdaggerq

from pdaggerq.parser import contracted_strings_to_tensor_terms


pq = pdaggerq.pq_helper("fermi")
pq.set_print_level(0)

pq.set_left_operators([['e4(i,j,k,l,d,c,b,a)']])

print('')
print('    < 0 | i* j* b a e(-T) H e(T) | 0> :')
print('')

# Add T2^2 terms *only* to net T4
pq.add_double_commutator(0.5,['v'],['t2'],['t2'])
pq.simplify()

# grab list of fully-contracted strings, then print
quad_residual_terms = pq.fully_contracted_strings()
for my_term in quad_residual_terms:
    print(my_term)

quad_residual_terms = contracted_strings_to_tensor_terms(quad_residual_terms)
for my_term in quad_residual_terms:
    print("#\t", my_term)
    print(my_term.einsum_string(update_val='quad_res',
                                output_variables=('a', 'b','c','d', 'i', 'j','k','l')))
    print()

pq.clear()

# Now, cap T2^2/2 with <ij||ab>
pq.set_left_operators([['e2(i,j,b,a)']])

print('')
print('    Net T2')
print('')

pq.add_commutator(1.0,['v'],['t4'])
pq.simplify()

e_t_terms = pq.fully_contracted_strings()
for my_term in e_t_terms:
    print(my_term)


e_t_terms = contracted_strings_to_tensor_terms(e_t_terms)
for my_term in e_t_terms:
    print("#\t", my_term)
    print(my_term.einsum_string(update_val='double_res',
                                output_variables=('a','b','i','j')))
    print()

pq.clear()
```

Is there a better way to build this diagram? I appreciate any help in advance.

**Comment by stephenyuwono** [comment]
Hello! First of all, I would like to confirm if you are trying to do this type of expression:

t*\_{fg}^{mn} v\_{fo}^{en} t\_{ae}^{im} t\_{bg}^{jo},

namely, (T2)* contracted with VN, to obtain intermediates that have all lines extending down, and contract with 1/2 T2^2.

If that is indeed the  case, you could use L_2 to emulate (T2)*. Unfortunately, it will give all possible contractions, so you will need to grep the cases where L2 shares 2 indices with VN and 1 index with each of the T2 vertices.

I guess you could also do this semi-manually, since the (T2)*VN intermediate is really behaving like an effective VN with all lines going down, so you could just derive VN 1/2 T2^2 diagrams with p*q and recognizing which terms you want, knowing than the VN generated by p*q is really  (T2)*VN.

**Comment by edeprince3** [comment]
If you want to use L_2 to emulate T2*, the following code would do that, but as @stephenyuwono said, you'll get all possible contractions, not just the diagram you want

```
import pdaggerq 
pq = pdaggerq.pq_helper("fermi")
pq.set_left_operators([['e2(i,j,b,a)', 'l2']])
pq.add_double_commutator(0.5, ['v'], ['t2'], ['t2'])
pq.simplify()

e_t_terms = contracted_strings_to_tensor_terms(e_t_terms)
for my_term in e_t_terms:
    print("#\t", my_term)
    print(my_term.einsum_string(update_val='double_res',
                                output_variables=('a','b','i','j')))
    print()

pq.clear()
```

**Comment by edeprince3** [comment]
I'm going to close this issue since the code isn't currently set up to return a specific diagram. @zww-4855 feel free to re-open or create a new one if you want to discuss more.

**Comment by zww-4855** [comment]
Thanks for the input everyone, I can handle it from here.  I apologize for lengthy delay in my response; I have been AFK. 

Dr. DePrince: I am wondering how easy it would be to extend the code for a class of diagrams similar to the one above. Maybe we can discuss further at Sanibel this year, as it is easier for me to write on a piece of paper. 

Take care all, 
Zack
